#!/usr/bin/env node
/**
 * WunderUI MCP server.
 *
 * Gives an AI coding agent (Claude Code, Cursor, Windsurf, Codex, Cline) direct
 * access to the WunderUI design system: tokens, the component inventory with
 * real prop signatures, templates and starter snippets — so it builds with the
 * library instead of reinventing it.
 *
 * The data comes from data/design.json, generated by
 * scripts/generate-agent-context.mjs out of the library source. Regenerate after
 * every release so the agent never sees a stale API.
 *
 * At start the server answers from the bundled copy at once, then fetches the
 * current design.json and DESIGN.md from wunderui.com in the background and
 * switches to them when they are at least as new. WUNDERUI_OFFLINE=1 skips that.
 */

import { readFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js"
import { z } from "zod"

const here = dirname(fileURLToPath(import.meta.url))
const dataDir = resolve(here, "../data")

let design = JSON.parse(readFileSync(resolve(dataDir, "design.json"), "utf8"))
let designMd = readFileSync(resolve(dataDir, "DESIGN.md"), "utf8")
let source = "bundled"

/** Swap in the live data from the site; any failure keeps the bundled copy. */
async function refresh() {
  if (process.env.WUNDERUI_OFFLINE === "1") return
  const site = (process.env.WUNDERUI_SITE ?? design.site ?? "https://wunderui.com").replace(/\/$/, "")
  try {
    const [json, md] = await Promise.all([
      fetch(`${site}/design.json`, { signal: AbortSignal.timeout(5000) }).then((r) => (r.ok ? r.json() : null)),
      fetch(`${site}/DESIGN.md`, { signal: AbortSignal.timeout(5000) }).then((r) => (r.ok ? r.text() : null)),
    ])
    if (!json || !Array.isArray(json.components) || !json.components.length || !md) return
    if (String(json.generatedAt ?? "") < String(design.generatedAt ?? "")) return
    design = json
    designMd = md
    source = site
    console.error(`wunderui MCP: using live data from ${site} (generated ${design.generatedAt})`)
  } catch {
    // offline or the site is down: the bundled copy is complete on its own
  }
}

/* ------------------------------------------------------------------ helpers */

const text = (value) => ({
  content: [{ type: "text", text: typeof value === "string" ? value : JSON.stringify(value, null, 2) }],
})

const normalize = (value) => String(value).toLowerCase().replace(/[^a-z0-9]/g, "")

/** Accepts an export name ("DataGrid"), a slug ("data-grid") or a title. */
function findComponent(name) {
  const key = normalize(name)
  return (
    design.components.find((component) => normalize(component.slug) === key) ??
    design.components.find((component) => component.exports.some((exported) => normalize(exported) === key)) ??
    design.components.find((component) => normalize(component.title) === key) ??
    null
  )
}

function matches(component, query) {
  const haystack = normalize(
    [component.title, component.slug, component.description, component.category, ...component.exports].join(" ")
  )
  return normalize(query)
    .split(/\s+/)
    .filter(Boolean)
    .every((term) => haystack.includes(term))
}

const STARTERS = {
  "app-shell": `import { AppLayout, Avatar, AvatarFallback, Navbar, Sidebar, SidebarHeading, SidebarItem, SidebarSection, SidebarUser } from "@wunderui/react"

export function Shell({ children }: { children: React.ReactNode }) {
  return (
    <AppLayout
      sidebar={
        <Sidebar
          logo={<span className="text-sm font-bold text-foreground">WunderUI</span>}
          footer={<SidebarUser name="Felix Brandt" email="felix@example.com" avatar={<Avatar size="sm"><AvatarFallback>FB</AvatarFallback></Avatar>} />}
        >
          <SidebarSection>
            <SidebarHeading>Workspace</SidebarHeading>
            <SidebarItem label="Overview" active />
            <SidebarItem label="Deals" />
          </SidebarSection>
        </Sidebar>
      }
      navbar={<Navbar logo={<span className="text-sm font-semibold text-foreground">Overview</span>} />}
    >
      {children}
    </AppLayout>
  )
}`,
  dashboard: `import { AreaChart, KPIGroup, StatCard, Widget } from "@wunderui/react"

const data = [
  { month: "Jul", Revenue: 26300 },
  { month: "Aug", Revenue: 28950 },
  { month: "Sep", Revenue: 34100 },
]

export function Dashboard() {
  return (
    <div className="flex flex-col gap-4">
      <KPIGroup columns={4}>
        <StatCard label="MRR" value="€34,100" delta="+14.2%" trend="up" trendGood prev="€29,850" />
        <StatCard label="Churn" value="1.8%" delta="-0.4pp" trend="down" trendGood prev="2.2%" />
      </KPIGroup>
      <Widget title="Revenue" description="Last three months">
        <AreaChart data={data} index="month" categories={["Revenue"]} height={240} />
      </Widget>
    </div>
  )
}`,
  table: `import { BadgeCell, CurrencyCell, DataGrid, UserCell, type DataGridColumn } from "@wunderui/react"

type Row = { id: string; name: string; email: string; status: "Paid" | "Pending"; amount: number }

const columns: DataGridColumn<Row>[] = [
  { key: "name", header: "Customer", sortable: true, filterValue: (row) => row.name,
    render: (row) => <UserCell name={row.name} email={row.email} initials={row.name.slice(0, 2)} /> },
  { key: "status", header: "Status", sortable: true, filterValue: (row) => row.status,
    render: (row) => <BadgeCell label={row.status} color={row.status === "Paid" ? "green" : "yellow"} badgeStyle="light" /> },
  { key: "amount", header: "Amount", sortable: true, filterValue: (row) => String(row.amount),
    render: (row) => <CurrencyCell value={row.amount} currency="EUR" /> },
]

export function Table({ rows }: { rows: Row[] }) {
  return <DataGrid columns={columns} data={rows} selectable searchable pageSize={10} />
}`,
  chat: `"use client"

import { useState } from "react"
import { ChainOfThought, ChatConversation, ChatMessage, ChatSource, ChatTool, PromptInput } from "@wunderui/react"

export function Assistant() {
  const [value, setValue] = useState("")
  return (
    <div className="flex flex-col gap-4">
      <ChatConversation>
        <ChatMessage role="user">Which accounts slipped out of Q3?</ChatMessage>
        <ChatMessage role="assistant">
          <ChainOfThought steps={["Filter deals by close date", "Compare against the forecast"]} />
          <ChatTool name="query_crm" status="done">3 accounts moved to Q4</ChatTool>
          <p>WunderUI, Halcyon Labs and Pergola Foods moved into Q4.</p>
          <ChatSource title="Pipeline snapshot" domain="crm.internal" index={1} />
        </ChatMessage>
      </ChatConversation>
      <PromptInput value={value} onValueChange={setValue} placeholder="Ask about your pipeline…" />
    </div>
  )
}`,
  theming: `/* Re-theme everything inside a subtree by overriding tokens. */
<div style={{ "--primary": "#1AD598", "--ring": "#1AD598", "--chart-1": "#1AD598" } as React.CSSProperties}>
  {children}
</div>

/* Or globally, in your Tailwind entry point, after the WunderUI import. */
:root { --primary: #1AD598; --ring: #1AD598; }
.dark { --primary: #4ADE9F; }`,
}

/* ------------------------------------------------------------------- server */

const server = new McpServer({
  name: "wunderui",
  version: design.version ?? "0.1.0",
})

server.registerTool(
  "list_components",
  {
    title: "List WunderUI components",
    description:
      "The WunderUI component inventory: name, category, plan (free or pro) and one-line description. Filter by category, plan or a free-text query. Call this first to find out whether a component already exists before building one by hand. On the Free plan use only components with plan \"free\".",
    inputSchema: {
      category: z.string().optional().describe(`One of: ${design.categories.join(", ")}`),
      query: z.string().optional().describe("Free text, matched against name, description and category"),
      plan: z.enum(["free", "pro"]).optional().describe("Only components of this plan. Free = open source under MIT (github.com/wunder-ui/wunderui); pro needs WunderUI Core or Pro."),
    },
  },
  async ({ category, query, plan }) => {
    let results = design.components
    if (plan) results = results.filter((component) => (component.tier ?? "pro") === plan)
    if (category) {
      const key = normalize(category)
      results = results.filter((component) => normalize(component.category) === key)
    }
    if (query) results = results.filter((component) => matches(component, query))

    return text({
      count: results.length,
      components: results.map((component) => ({
        name: component.exports[0] ?? component.title,
        category: component.category,
        plan: component.tier ?? "pro",
        description: component.description,
        docs: component.docs,
      })),
    })
  }
)

server.registerTool(
  "get_component",
  {
    title: "Get a WunderUI component",
    description:
      "Everything needed to use one component correctly: its exported names, the TypeScript prop signature straight from the build, the import line and a link to its documentation page.",
    inputSchema: {
      name: z.string().describe('Export name ("DataGrid"), slug ("data-grid") or title ("Data Grid")'),
    },
  },
  async ({ name }) => {
    const component = findComponent(name)
    if (!component) {
      const suggestions = design.components
        .filter((candidate) => matches(candidate, name))
        .slice(0, 5)
        .map((candidate) => candidate.exports[0] ?? candidate.title)
      return text({
        error: `No component named "${name}".`,
        didYouMean: suggestions,
        hint: "Call list_components to see every component.",
      })
    }
    return text({
      name: component.exports[0],
      title: component.title,
      category: component.category,
      plan: component.tier ?? "pro",
      planNote: (component.tier ?? "pro") === "free" ? "Free: MIT source, any project — fetch it from sourceRaw." : "Needs WunderUI Core or Pro.",
      source: component.source ?? undefined,
      sourceRaw: component.sourceRaw ?? undefined,
      description: component.description,
      import: `import { ${component.exports.slice(0, 4).join(", ")} } from "${design.name}"`,
      exports: component.exports,
      example: component.example ?? undefined,
      props: component.props ?? "No generated signature — see the documentation page.",
      docs: component.docs,
    })
  }
)

server.registerTool(
  "get_tokens",
  {
    title: "Get WunderUI design tokens",
    description:
      "The design tokens for light and dark, in the format you need. Use these instead of hardcoding colours; overriding them is how WunderUI is themed.",
    inputSchema: {
      format: z.enum(["json", "css", "tailwind"]).default("json").describe("json, a CSS block, or Tailwind @theme mappings"),
      theme: z.enum(["light", "dark", "both"]).default("both"),
    },
  },
  async ({ format, theme }) => {
    const wanted =
      theme === "both" ? design.tokens : { [theme]: design.tokens[theme] }

    if (format === "json") return text(wanted)

    if (format === "css") {
      const block = (selector, tokens) =>
        `${selector} {\n${Object.entries(tokens)
          .map(([name, value]) => `  ${name}: ${value};`)
          .join("\n")}\n}`
      const parts = []
      if (wanted.light) parts.push(block(":root", wanted.light))
      if (wanted.dark) parts.push(block(".dark", wanted.dark))
      return text(parts.join("\n\n"))
    }

    const mappings = Object.keys(design.tokens.light)
      .filter((name) => !name.startsWith("--radius"))
      .map((name) => `  --color-${name.slice(2)}: var(${name});`)
      .join("\n")
    return text(`@theme inline {\n${mappings}\n}`)
  }
)

server.registerTool(
  "get_design_md",
  {
    title: "Get the WunderUI DESIGN.md",
    description:
      "The complete design context as one markdown document: install steps, the rules an agent should follow, every token, the component inventory with props, and starter snippets. Pull this once at the start of a build.",
    inputSchema: {
      section: z
        .enum(["all", "rules", "donts", "tasks", "tokens", "inventory", "reference", "props", "templates", "starters"])
        .default("all")
        .describe(
          "Return the whole document or just one section. 'tasks' maps an intent to a component, 'donts' holds the do/don't pairs, 'reference' every component with example and props."
        ),
    },
  },
  async ({ section }) => {
    if (section === "all") return text(designMd)
    const headings = {
      rules: "## Rules for agents",
      donts: "## Do and don't",
      tasks: "## Task → component",
      tokens: "## Tokens",
      inventory: "## Component inventory",
      reference: "## Reference",
      props: "## Reference",
      templates: "## Templates",
      starters: "## Starting points",
    }
    const heading = headings[section]
    const start = designMd.indexOf(heading)
    if (start === -1) return text(designMd)
    const next = designMd.indexOf("\n## ", start + heading.length)
    return text(designMd.slice(start, next === -1 ? undefined : next).trim())
  }
)

server.registerTool(
  "list_templates",
  {
    title: "List WunderUI page templates",
    description:
      "Full pages assembled only from WunderUI components — a dashboard, a settings page, an AI inbox and a sign-in screen. Start from one of these instead of an empty file.",
    inputSchema: {},
  },
  async () => text({ count: design.templates.length, templates: design.templates })
)

server.registerTool(
  "get_starter",
  {
    title: "Get a WunderUI starter snippet",
    description:
      "Copy-paste TSX for a common composition, wired with the correct props: an application shell, a dashboard row, a data grid, an AI chat, or the theming pattern.",
    inputSchema: {
      kind: z.enum(["app-shell", "dashboard", "table", "chat", "theming"]),
    },
  },
  async ({ kind }) => text(STARTERS[kind])
)

server.registerTool(
  "get_library_info",
  {
    title: "Get WunderUI package info",
    description:
      "Package name and version, install commands, the stack it is built on, and how many components, categories and templates exist.",
    inputSchema: {},
  },
  async () =>
    text({
      name: design.name,
      version: design.version,
      description: design.description,
      site: design.site,
      generatedAt: design.generatedAt,
      dataSource: source,
      install: design.install,
      stack: design.stack,
      counts: design.counts,
      categories: design.categories,
    })
)

/* --------------------------------------------------------------------- run */

async function main() {
  const transport = new StdioServerTransport()
  await server.connect(transport)
  refresh()
  console.error(
    `wunderui MCP ready — ${design.counts.components} components, ${design.counts.templates} templates, generated ${design.generatedAt}`
  )
}

main().catch((error) => {
  console.error("wunderui MCP failed to start:", error)
  process.exit(1)
})
